# Generated by Django 5.0.1 on 2024-02-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('item_qty', models.IntegerField()),
                ('item_price', models.FloatField()),
                ('order_id', models.IntegerField()),
                ('order_status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('item_qty', models.IntegerField()),
                ('item_price', models.FloatField()),
                ('order_id', models.IntegerField()),
                ('order_status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('item_qty', models.IntegerField()),
                ('item_price', models.FloatField()),
                ('order_id', models.IntegerField()),
                ('order_status', models.BooleanField(null=True)),
            ],
        ),
    ]
