# Generated by Django 5.0.1 on 2024-02-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('item_qty', models.IntegerField()),
                ('item_price', models.FloatField()),
                ('order_id', models.IntegerField()),
                ('order_status', models.BooleanField(null=True)),
                ('user_id', models.CharField(max_length=10)),
            ],
        ),
    ]
