# Generated by Django 5.0.1 on 2024-04-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_1',
        ),
        migrations.DeleteModel(
            name='User_2',
        ),
        migrations.DeleteModel(
            name='User_3',
        ),
    ]
