# Generated by Django 5.0.7 on 2024-07-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0005_customer_invoice_order_user_user_invoice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_vat_valid',
            field=models.BooleanField(),
        ),
    ]
