# Generated by Django 5.0.7 on 2024-07-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0006_alter_customer_customer_vat_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
    ]
