# Generated by Django 5.0.7 on 2024-08-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0007_remove_invoice_customer_id_remove_order_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=models.CharField(max_length=15),
        ),
    ]
