# Generated by Django 5.0.7 on 2024-08-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0008_alter_customer_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_recieved', models.IntegerField()),
                ('sum_payer', models.CharField(max_length=100)),
                ('sum_reg', models.CharField(max_length=10)),
                ('sum_aim', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=10)),
            ],
        ),
    ]
