# Generated by Django 5.0.7 on 2024-08-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0009_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='sum_recieved',
            new_name='sum_received',
        ),
    ]
