# Generated by Django 5.0.7 on 2024-08-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0011_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_invoice_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
