# Generated by Django 5.0.7 on 2024-08-08 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0012_invoice_invoice_invoice_invoice_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_name',
        ),
    ]
