# Generated by Django 5.0.7 on 2024-08-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0013_remove_invoice_invoice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='sum_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='customer_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
