# Generated by Django 5.0.7 on 2024-08-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0014_balance_sum_date_alter_balance_customer_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
