# Generated by Django 5.0.7 on 2024-08-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0015_delete_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_received', models.IntegerField()),
                ('sum_date', models.DateField()),
                ('sum_payer', models.CharField(max_length=100)),
                ('sum_reg', models.CharField(max_length=10)),
                ('sum_aim', models.CharField(max_length=100)),
                ('customer_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
