# Generated by Django 5.0.7 on 2024-08-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0016_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='sum_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(),
        ),
    ]
