# Generated by Django 5.0.7 on 2024-08-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0017_alter_balance_sum_date_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='sum_counted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
