# Generated by Django 5.0.7 on 2024-08-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0020_alter_balance_sum_counted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='sum_counted',
            field=models.BooleanField(),
        ),
    ]
