# Generated by Django 5.0.7 on 2024-08-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0021_alter_balance_sum_counted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='sum_aim',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='sum_counted',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='sum_reg',
        ),
    ]
