# Generated by Django 5.0.7 on 2024-08-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0022_remove_balance_sum_aim_remove_balance_sum_counted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='sum_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
