# Generated by Django 5.0.7 on 2024-08-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0023_alter_balance_sum_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_vat',
            field=models.CharField(max_length=15),
        ),
    ]
