# Generated by Django 5.0.7 on 2024-08-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0024_alter_customer_customer_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='sum_aim',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
