# Generated by Django 5.0.7 on 2024-08-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0027_alter_balance_sum_aim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='sum_received',
            field=models.FloatField(),
        ),
    ]
